name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment and install dependencies
        run: |
          uv venv .venv --python 3.11
          source .venv/bin/activate
          uv pip install .
          uv pip install -e ".[dev]"

      - name: Run linting
        run: |
          source .venv/bin/activate
          make lint

      - name: Run tests
        run: |
          source .venv/bin/activate
          make tests
